Eva.UI.Web/Areas/Painel/Controllers/ArquivosController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Eva.Aplicacao;
using Eva.Dominio;
using Eva.UI.Web.Helpers;
using System.Net;

namespace Eva.UI.Web.Areas.Painel.Controllers
{
    public class ArquivosController : Controller
    {
        public ActionResult Index(string id, string plugin, int? pagina, string query, string urlImagemSalvar)
        {
            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(plugin))
                return RedirectToAction("Index", "Home", new { area = "Painel" });

            ViewBag.urlVoltar = string.Empty;
            ViewBag.urlTitulo = string.Empty;

            //salva imagem buscada na web, se for o caso
            GetImage(urlImagemSalvar, id, plugin.ToLower());

            var arquivoViewModel = new ArquivoViewModel();

            var page = pagina ?? 0;
            const int registroPorPagina = 8;
            var pularRegistros = page * registroPorPagina;

            switch (plugin.ToLower())
            {
                case "noticia":
                    var noticia = Fabrica.NoticiaAplicacaoMongo().ListarPorId(id);
                    arquivoViewModel.Arquivos = noticia.Arquivos.Skip(pularRegistros).Take(registroPorPagina) ?? new List<Arquivo>();
                    arquivoViewModel.Id = noticia.Id;
                    arquivoViewModel.Titulo = noticia.Titulo;
                    arquivoViewModel.Plugin = plugin;
                    ViewBag.urlTitulo = "Notícias";
                    ViewBag.urlVoltar = Url.Action("Index", "Noticia");
                    break;

                case "evento":
                    var evento = Fabrica.EventoAplicacaoMongo().ListarPorId(id);
                    arquivoViewModel.Arquivos = evento.Arquivos.Skip(pularRegistros).Take(registroPorPagina) ?? new List<Arquivo>();
                    arquivoViewModel.Id = evento.Id;
                    arquivoViewModel.Titulo = evento.Titulo;
                    arquivoViewModel.Plugin = plugin;
                    ViewBag.urlTitulo = "Eventos";
                    ViewBag.urlVoltar = Url.Action("Index", "Evento");
                    break;
            }

            if (Request.IsAjaxRequest())
                return PartialView("listaImagens", arquivoViewModel);

            //busca bing
            arquivoViewModel.Query = query;

            var retornoBusca = Imagem.BuscarImagemNaWeb(query);
            if (!retornoBusca.Any())
                this.Flash("Sua busca por imagens não retornou nenhum resultado!", FlashEnum.Error);
            arquivoViewModel.RetornoBusca = retornoBusca;



            return View(arquivoViewModel);
        }



        public ActionResult Enviar(string id, string plugin)
        {
            Session["logos"] = null;

            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(plugin))
                return RedirectToAction("Index", "Home", new { area = "Painel" });

            ViewBag.urlVoltar = string.Empty;
            ViewBag.urlTitulo = string.Empty;

            var arquivoViewModel = new ArquivoViewModel();

            switch (plugin.ToLower())
            {
                case "noticia":
                    var noticia = Fabrica.NoticiaAplicacaoMongo().ListarPorId(id);
                    arquivoViewModel.Arquivos = noticia.Arquivos ?? new List<Arquivo>();
                    arquivoViewModel.Id = noticia.Id;
                    arquivoViewModel.Titulo = noticia.Titulo;
                    arquivoViewModel.Plugin = plugin;
                    ViewBag.urlTitulo = "Notícias";
                    ViewBag.urlVoltar = Url.Action("Index", "Noticia");
                    break;
                case "evento":
                    var evento = Fabrica.EventoAplicacaoMongo().ListarPorId(id);
                    arquivoViewModel.Arquivos = evento.Arquivos ?? new List<Arquivo>();
                    arquivoViewModel.Id = evento.Id;
                    arquivoViewModel.Titulo = evento.Titulo;
                    arquivoViewModel.Plugin = plugin;
                    ViewBag.urlTitulo = "Eventos";
                    ViewBag.urlVoltar = Url.Action("Index", "Evento");
                    break;
            }

            ViewBag.Logos = Fabrica.LogoAplicacaoMongo().ListarTodos().ToList();

            return View(arquivoViewModel);
        }

        public JsonResult Excluir(string id, string plugin, string idArquivo)
        {
            Arquivo arquivo, arquivoCapa;
            switch (plugin.ToLower())
            {
                case "noticia":
                    var noticia = Fabrica.NoticiaAplicacaoMongo().ListarPorId(id);
                    arquivo = noticia.Arquivos.FirstOrDefault(x => x.Id == idArquivo);

                    noticia.Arquivos.Remove(arquivo);
                    Imagem.ExcluirArquivo(arquivo.Nome, plugin);

                    noticia.Arquivos = Imagem.OrdenarArquivos(noticia.Arquivos.OrderBy(x => x.Ordem).Select(x => x.Id), noticia.Arquivos);

                    arquivoCapa = noticia.Arquivos.FirstOrDefault(x => x.Ordem == 1);
                    if (arquivoCapa != null)
                        Imagem.GeraArquivosBaseadoEmListaDeTamanhos(arquivoCapa.Nome, plugin, ImagensLayout.Noticias);

                    Fabrica.NoticiaAplicacaoMongo().Salvar(noticia);
                    break;
                case "evento":
                    var evento = Fabrica.EventoAplicacaoMongo().ListarPorId(id);
                    arquivo = evento.Arquivos.FirstOrDefault(x => x.Id == idArquivo);

                    evento.Arquivos.Remove(arquivo);
                    Imagem.ExcluirArquivo(arquivo.Nome, plugin);

                    evento.Arquivos = Imagem.OrdenarArquivos(evento.Arquivos.OrderBy(x => x.Ordem).Select(x => x.Id), evento.Arquivos);

                    arquivoCapa = evento.Arquivos.FirstOrDefault(x => x.Ordem == 1);
                    if (arquivoCapa != null)
                        Imagem.GeraArquivosBaseadoEmListaDeTamanhos(arquivoCapa.Nome, plugin, ImagensLayout.Eventos);

                    Fabrica.EventoAplicacaoMongo().Salvar(evento);
                    break;

            }

            return Json("", JsonRequestBehavior.AllowGet);
        }

        public JsonResult ConfigurarLogo(LogoAplicarViewModel logos)
        {
            Session["logos"] = logos;
            return Json("", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Upload(int? chunk, int? chunks, string name, string plugin, string id)
        {
            var fileUpload = Request.Files[0];

            if (!Imagem.Upload(fileUpload, plugin, name, chunk, chunks)) return Content("Success", "text/plain");

            int ordem;
            switch (plugin.ToLower())
            {
                case "noticia":
                    var noticia = Fabrica.NoticiaAplicacaoMongo().ListarPorId(id);

                    ordem = (noticia.Arquivos.Any()) ? noticia.Arquivos.Max(x => x.Ordem) + 1 : 1;

                    noticia.Arquivos.Add(new Arquivo() { Nome = name, Legenda = noticia.Titulo, Ordem = ordem });
                    Fabrica.NoticiaAplicacaoMongo().Salvar(noticia);

                    if (ordem == 1)
                        Imagem.GeraArquivosBaseadoEmListaDeTamanhos(name, plugin, ImagensLayout.Noticias);

                    break;

                case "evento":
                    var evento = Fabrica.EventoAplicacaoMongo().ListarPorId(id);

                    ordem = (evento.Arquivos.Any()) ? evento.Arquivos.Max(x => x.Ordem) + 1 : 1;

                    evento.Arquivos.Add(new Arquivo() { Nome = name, Legenda = evento.Titulo, Ordem = ordem });
                    Fabrica.EventoAplicacaoMongo().Salvar(evento);

                    if (ordem == 1)
                        Imagem.GeraArquivosBaseadoEmListaDeTamanhos(name, plugin, ImagensLayout.Eventos);

                    break;
            }

            //Aplico o logo, ou redimensiona, salva
            var posicaoLogo = (LogoAplicarViewModel)Session["logos"] ?? new LogoAplicarViewModel();

            var pLogo = new List<PosicaoLogo>();

            #region Todo: Refatorar isso

            if (posicaoLogo.Logo1 != null)
            {
                pLogo.Add(new PosicaoLogo()
                {
                    IdLogo = posicaoLogo.Logo1,
                    PosicaoHorizontal = "Left", //"Left", "Right", or "Center".
                    PosicaoVertical = "Top" //"Top", "Middle", or "Bottom"
                });
            }
            if (posicaoLogo.Logo2 != null)
            {
                pLogo.Add(new PosicaoLogo()
                {
                    IdLogo = posicaoLogo.Logo2,
                    PosicaoHorizontal = "Center",
                    PosicaoVertical = "Top"
                });
            }

            if (posicaoLogo.Logo3 != null)
            {
                pLogo.Add(new PosicaoLogo()
                {
                    IdLogo = posicaoLogo.Logo3,
                    PosicaoHorizontal = "Right",
                    PosicaoVertical = "Top"
                });
            }

            if (posicaoLogo.Logo4 != null)
            {
                pLogo.Add(new PosicaoLogo()
                {
                    IdLogo = posicaoLogo.Logo4,
                    PosicaoHorizontal = "Left",
                    PosicaoVertical = "Middle"
                });
            }

            if (posicaoLogo.Logo5 != null)
            {
                pLogo.Add(new PosicaoLogo()
                {
                    IdLogo = posicaoLogo.Logo5,
                    PosicaoHorizontal = "Center",
                    PosicaoVertical = "Middle"
                });
            }

            if (posicaoLogo.Logo6 != null)
            {
                pLogo.Add(new PosicaoLogo()
                {
                    IdLogo = posicaoLogo.Logo6,

Eva.UI.Web/Areas/Painel/Controllers/NoticiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eva.Aplicacao;
using Eva.Dominio;
using System.ComponentModel.DataAnnotations;
using Eva.UI.Web.Helpers;
using PagedList;

namespace Eva.UI.Web.Areas.Painel.Controllers
{
    public class NoticiaController : Controller
    {
        private readonly NoticiaAplicacao noticiaApp;
        private readonly CategoriaAplicacao categoriaApp;
        private readonly NoticiaZonaAplicacao noticiaZonaApp;
        private readonly FonteAplicacao fonteApp;
        private readonly LocalAplicacao localApp;

        public NoticiaController()
        {
            noticiaApp = Fabrica.NoticiaAplicacaoMongo();
            categoriaApp = Fabrica.CategoriaAplicacaoMongo();
            noticiaZonaApp = Fabrica.NoticiaZonaAplicacaoMongo();
            fonteApp = Fabrica.FonteAplicacaoMongo();
            localApp = Fabrica.LocalAplicacaoMongo();

        }
        public ActionResult Index(int? page)
        {
            var numeroDaPagina = page ?? 1;
            var listaPaginada = noticiaApp.ListarTodos().OrderByDescending(x=>x.Data).ToPagedList(numeroDaPagina, 10);

            return View(listaPaginada);
        }

        public ActionResult Editar(string id)
        {
            ViewBag.Categorias = categoriaApp.ListarTodos().ToList();
            ViewBag.Zonas = noticiaZonaApp.ListarTodos().ToList();

            if (string.IsNullOrEmpty(id))
                return View(new NoticiaViewModel());

            var noticia = noticiaApp.ListarPorId(id);
            if (noticia == null)
            {
                this.Flash("Noticia não encontrado!", FlashEnum.Error);
                return View(new NoticiaViewModel());
            }

            var noticiaViewModel = new NoticiaViewModel()
            {
                Id = noticia.Id,
                Titulo = noticia.Titulo,
                Antetitulo = noticia.Antetitulo,
                Categoria = noticia.Categoria,
                CategoriaId = noticia.Categoria.Id,
                Zona = noticia.Zona,
                ZonaId = noticia.Zona.Id,
                Conteudo = noticia.Conteudo,
                Data = noticia.Data,
                ExibirComentarios = noticia.ExibirComentarios,
                Publicado = noticia.Publicado,
                Fonte = noticia.Fonte,
                FonteNome = noticia.Fonte.Nome,
                Local = noticia.Local,
                LocalNome = noticia.Local.Nome,
                Resumo = noticia.Resumo,
                Arquivos = noticia.Arquivos
            };

            return View(noticiaViewModel);
        }

        [HttpPost]
        public ActionResult Editar(NoticiaViewModel noticia)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categorias = categoriaApp.ListarTodos().ToList();
                ViewBag.Zonas = noticiaZonaApp.ListarTodos().ToList();
                return View(noticia);
            }

            var noticiaSalvar = new Noticia
            {
                Id = noticia.Id,
                Titulo = noticia.Titulo,
                Antetitulo = noticia.Antetitulo,
                Categoria = noticia.Categoria,
                Conteudo = noticia.Conteudo,
                Data = noticia.Data,
                ExibirComentarios = noticia.ExibirComentarios,
                Publicado = noticia.Publicado,
                Fonte = noticia.Fonte,
                Local = noticia.Local,
                Resumo = noticia.Resumo,
                Zona = noticia.Zona
            };

            noticiaSalvar.Categoria = categoriaApp.ListarPorId(noticia.CategoriaId);
            noticiaSalvar.Zona = noticiaZonaApp.ListarPorId(noticia.ZonaId);
            
            var fonte = fonteApp.ListarPorNome(noticia.FonteNome);
            if (fonte != null)
            {
                noticiaSalvar.Fonte = fonte;
            }
            else
            {
                var fonteNova = new Fonte() {Nome = noticia.FonteNome};
                fonteApp.Salvar(fonteNova);
                noticiaSalvar.Fonte = fonteNova;
            }

            var local = localApp.ListarPorNome(noticia.LocalNome);
            if (local != null)
            {
                noticiaSalvar.Local = local;
            }
            else
            {
                var localNova = new Local() { Nome = noticia.LocalNome };
                localApp.Salvar(localNova);
                noticiaSalvar.Local = localNova;
            }

            if (!string.IsNullOrEmpty(noticia.Id))
            {
                var noticiaBanco = noticiaApp.ListarPorId(noticia.Id);
                noticiaSalvar.Arquivos = noticiaBanco.Arquivos;
                noticiaSalvar.Hits = noticiaBanco.Hits;
            }


            noticiaApp.Salvar(noticiaSalvar);
            this.Flash("Noticia Salva com Sucesso!");
            return RedirectToAction("Index");
        }

        public JsonResult Excluir(string id)
        {
            var item = Fabrica.NoticiaAplicacaoMongo().ListarPorId(id);

            if (item == null) return Json("", JsonRequestBehavior.AllowGet);

            Imagem.ExcluirArquivo(item.Arquivos, "noticia");
            Fabrica.NoticiaAplicacaoMongo().Excluir(id);

            return Json("", JsonRequestBehavior.AllowGet);
        }
    }

    public class NoticiaViewModel
    {
        public string Id { get; set; }
        public string Titulo { get; set; }
        public string CategoriaId { get; set; }
        public Categoria Categoria { get; set; }
        public string ZonaId { get; set; }
        public NoticiaZona Zona { get; set; }
        public string Antetitulo { get; set; }
        public string Resumo { get; set; }
        public string Conteudo { get; set; }
        public DateTime Data { get; set; }
        public Fonte Fonte { get; set; }
        public string FonteNome { get; set; }
        public Local Local { get; set; }
        public string LocalNome { get; set; }
        public bool Publicado { get; set; }
        public bool ExibirComentarios { get; set; }
        public List<Arquivo> Arquivos { get; set; }

    }
}

Eva.UI.Web/Areas/Painel/Views/Noticia/Index.cshtml
@using Eva.Dominio
@using PagedList.Mvc
@model PagedList.IPagedList<Eva.Dominio.Noticia>
<div class="col-md-12">
    <!--breadcrumbs start -->
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home", new { Area = "Painel" })"><i class="fa fa-home"></i> Inicio</a></li>
        <li class="active">Notícias</li>
    </ul>
    <!--breadcrumbs end -->
</div>

<div class="col-md-12">
    @Flash.FlashMessage(TempData)
</div>

<div class="col-sm-12">
    <section class="panel">
        <header class="panel-heading">
            Notícias
        </header>
        <div class="panel-body">
            <div class="adv-table editable-table ">
                <div class="clearfix" style="margin-bottom: 15px;">
                    <div class="btn-group">
                        <a href="@Url.Action("Editar")" class="btn btn-primary">
                            Nova notícias <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    <div class="btn-group pull-right">
                        <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            Tools <i class="fa fa-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="#">Print</a></li>
                            <li><a href="#">Save as PDF</a></li>
                            <li><a href="#">Export to Excel</a></li>
                        </ul>
                    </div>
                </div>

                <div id="editable-sample_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <table class="table table-hover general-table">
                        <thead>
                            <tr role="row">
                                <th></th>
                                <th>Titulo</th>
                                <th>Categoria</th>
                                <th>Zona</th>
                                <th>Data</th>
                                <th>Publicado</th>
                                <th style="width: 155px">Opções</th>
                            </tr>
                        </thead>

                        <tbody>
                         
                            @if (Model.Any())
                            {
                                foreach (var noticia in Model)
                                {
                                    <tr id="id_@noticia.Id">
                                        <td>
                                            @{
                                                var arquivo = noticia.Arquivos.FirstOrDefault() ?? new Arquivo();
                                            }
                                            <img src="@Foto.Placehold(arquivo.Nome, "75x75", "Noticia", "75x75_")" width="40" height="40" id="@noticia.Id" data-pathimg="@Foto.Placehold(arquivo.Nome,"250x250","noticia")" data-nome="@noticia.Titulo" />
                                        </td>
                                        <td>@noticia.Titulo</td>
                                        <td>@noticia.Categoria.Nome</td>
                                        <td>@noticia.Zona.Nome</td>
                                        <td>@noticia.Data.ToString("dd/MM/yyyy HH:mm")</td>
                                        <td>@noticia.Publicado</td>


                                        <td>
                                            <a href="@Url.Action("Index","Arquivos", new { id = noticia.Id, plugin="noticia" })" class="btn btn-white active tooltips" data-original-title="Editar" data-toggle="tooltip">
                                                <i class="fa fa-camera"></i>
                                            </a>
                                            <a href="@Url.Action("Editar", new { Id = noticia.Id })" class="btn btn-white active tooltips" data-original-title="Editar" data-toggle="tooltip">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            <a href="#" data-id="@noticia.Id" class="btn btn-white active" data-toggle="modal" data-target="#confimarExclusao">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="7">Não foi encontrado dados para a exibição</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="dataTables_paginate paging_bootstrap pagination pull-left">
                                @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }),
                                    new PagedListRenderOptions
                                    {
                                        UlElementClasses = Enumerable.Empty<string>(),
                                        DisplayPageCountAndCurrentLocation = true,
                                        PageCountAndCurrentLocationFormat = "Página {0} de {1}"

                                    })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Modal Excluir Arquivos -->
            <div class="modal fade" id="confimarExclusao" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Confirmar exclusão</h4>
                        </div>

                        <div class="modal-body row">

                            <div class="col-md-5 img-modal">
                                <img class="imgModal" src="" alt="">
                            </div>
                            <div class="col-md-7">
                                <h4 class="modal-title" id="myModalLabel">Deseja realmente excluir este item?</h4>
                                <br />
                                <h5 class="editNome"></h5>
                            </div>
                        </div>
                        <div class="modal-footer">

                            <button class="btn btn-danger" type="button" id="btnExcluirModal">Excluir</button>
                            <button data-dismiss="modal" aria-hidden="true" class="btn" type="button">Cancelar</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal-->

        </div>
    </section>
</div>
<script type="text/javascript">
    $(document).ready(function () {

        var itemAtual = {};
        $('#confimarExclusao').on('show.bs.modal', function (e) {
            carregaItemAtual(e.relatedTarget);

            $(this).find('.imgModal').attr('src', itemAtual.pathimg);
            $('.editNome').text(itemAtual.nome);

        });

        $('#btnExcluirModal').click(function () {
            $('#id_' + itemAtual.id).remove();

            $.ajax({
                url: "@Url.Action("Excluir")",
                type: "POST",
                data: JSON.stringify({ id: itemAtual.id }),
                contentType: 'application/json'
            });

            $('#confimarExclusao').modal('hide');
        });

        function carregaItemAtual(target) {
            itemAtual.id = $(target).data('id');
            itemAtual.pathimg = $('#' + itemAtual.id).data('pathimg');
            itemAtual.nome = $('#' + itemAtual.id).data('nome');
        }
    });

</script>