Eva.UI.Web/Areas/Painel/Controllers/EventoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eva.Aplicacao;
using Eva.Dominio;
using System.ComponentModel.DataAnnotations;
using Eva.UI.Web.Helpers;
using PagedList;

namespace Eva.UI.Web.Areas.Painel.Controllers
{
    public class EventoController : Controller
    {
        private readonly EventoAplicacao eventoApp;
        
        public EventoController()
        {
            eventoApp = Fabrica.EventoAplicacaoMongo();
            

        }
        public ActionResult Index(int? page)
        {
            var numeroDaPagina = page ?? 1;
            var listaPaginada = eventoApp.ListarTodos().OrderByDescending(x => x.Data).ToPagedList(numeroDaPagina, 10);

            return View(listaPaginada);
        }

        public ActionResult Editar(string id)
        {
            if (string.IsNullOrEmpty(id))
                return View(new EventoViewModel());

            var evento = eventoApp.ListarPorId(id);
            if (evento == null)
            {
                this.Flash("Evento não encontrado!", FlashEnum.Error);
                return View(new EventoViewModel());
            }

            var eventoViewModel = new EventoViewModel()
            {
                Id = evento.Id,
                Titulo = evento.Titulo,
                Descricao = evento.Descricao,
                Local = evento.Local,
                Data = evento.Data,
                Creditos = evento.Creditos,
                Publicado = evento.Publicado,
            };

            return View(eventoViewModel);
        }

        [HttpPost]
        public ActionResult Editar(EventoViewModel evento)
        {
            if (!ModelState.IsValid)
            {
                return View(evento);
            }

            var eventoSalvar = new Evento
            {
                Id = evento.Id,
                Titulo = evento.Titulo,
                Descricao = evento.Descricao,
                Local = evento.Local,
                Data = evento.Data,
                Creditos = evento.Creditos,
                Publicado = evento.Publicado,
            };

            if (!string.IsNullOrEmpty(evento.Id))
            {
                var eventoBanco = eventoApp.ListarPorId(evento.Id);
                eventoSalvar.Arquivos = eventoBanco.Arquivos;
                eventoSalvar.Hits = eventoBanco.Hits;
            }


            eventoApp.Salvar(eventoSalvar);
            this.Flash("Evento Salvo com Sucesso!");
            return RedirectToAction("Index");
        }

        public JsonResult Excluir(string id)
        {
            var item = Fabrica.EventoAplicacaoMongo().ListarPorId(id);
           
            if (item == null) return Json("", JsonRequestBehavior.AllowGet);
            
            Imagem.ExcluirArquivo(item.Arquivos, "evento");
            Fabrica.EventoAplicacaoMongo().Excluir(id);
            return Json("", JsonRequestBehavior.AllowGet);
        }
    }

    public class EventoViewModel
    {
        public string Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public string Local { get; set; }
        public DateTime Data { get; set; }
        public string Creditos { get; set; }
        public int Hits { get; set; }
        public bool Publicado { get; set; }

    }
}

Eva.UI.Web/Controllers/EventoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eva.Aplicacao;
using Eva.Dominio;
using PagedList;

namespace Eva.UI.Web.Controllers
{
    [RoutePrefix("evento")]
    public class EventoController : Controller
    {
        [Route("{page:int?}")]
        public ActionResult Index(int? page)
        {
            //todo: checar se categoria existe ou notFound
            var numeroDaPagina = page ?? 1;
            var ultimas = Fabrica.EventoAplicacaoMongo().ListarPublicadas();
            return View(ultimas.OrderByDescending(x => x.Data).ToPagedList(numeroDaPagina, 10));
        }

        [Route("{ano}/{mes}/{dia}/{slug}/{page:int?}")]
        public ActionResult Ler(string slug, int ano, int mes, int dia,int? page)
        {
            var data = new DateTime(ano, mes, dia);
            var evento = Fabrica.EventoAplicacaoMongo().Ler(slug,data);
            if (evento == null)
                return HttpNotFound();

            var numeroDaPagina = page ?? 1;
            var vm = new EventoLerViewModel
            {
                Evento = evento,
                Arquivos = evento.Arquivos.OrderBy(x=>x.Ordem).ToPagedList(numeroDaPagina,10)
            };

            return View(vm);
        }
    }

    public class EventoLerViewModel
    {
        public Evento Evento { get; set; }
        public IPagedList<Arquivo> Arquivos { get; set; }
    }
}

Eva.UI.Web/Views/Evento/Index.cshtml
@using Eva.Dominio
@using PagedList.Mvc
@model PagedList.IPagedList<Eva.Dominio.Evento>

<section class="bloco-largura left mgn-top-20px">
    <h2 class="titulo-28px mgn-left-10px fui-camera">EVENTOS</h2>
    <ul class="eventos-lista left">
        @foreach (var evento in Model.Take(10))
        {
            <li>
                <div class="topo-eventos">
                    <p class="data left">@evento.Data.ToShortDateString()</p>
                    <p class="quant-fotos right fui-camera">@evento.Arquivos.Count() fotos</p>
                </div>
                <a href="@Url.Action("Ler", "Evento", new { Area = "", slug = evento.Slug, ano = evento.Data.Year, mes = evento.Data.Month, dia = evento.Data.Day, page=1})" title="@evento.Titulo">
                    <figure>
                        @{
            var arquivo = evento.Arquivos.FirstOrDefault() ?? new Arquivo();
                        }
                        <img src="@Foto.Placehold(arquivo.Nome, "180x102", "Evento" , "180x102_" )" width="220" height="124" />
                    </figure>
                    <p class="hora left fui-time">@evento.Data.ToShortTimeString()</p>
                    <p class="local right fui-location">@evento.Local</p>
                    <p class="desc left">@evento.Titulo</p>
                </a>
            </li>
        }
    </ul>
</section>
<div class="paginacao left mgn-top-20px">
   @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>

Eva.UI.Web/Views/Evento/Ler.cshtml
@using PagedList.Mvc
@model Eva.UI.Web.Controllers.EventoLerViewModel
<div class="banner-1184px right mgn-right-10px mgn-top-20px">
    <div class="banner-728px left">
        <div class="texto-vertical left"></div>
        <div class="banner right">
            <figure>
                <a href="#" title="Título do banner">
                    <img src="img/banners/728x90px/img1.png" alt="">
                </a>
            </figure>
        </div>
    </div>
    <div class="banner-417px right">
        <div class="texto-vertical left"></div>
        <div class="banner right">
            <figure>
                <a href="#" title="Título do banner">
                    <img src="img/banners/394x90px/img2.png" alt="">
                </a>
            </figure>
        </div>
    </div>
</div>
<section class="bloco-largura-940px mgn-left-10px left mgn-top-20px">
    <a href="eventos.html" title="EVENTOS">
        <p class="titulo-28px fui-camera">EVENTOS</p>
    </a>
    <div class="barra-info">
        <p class="data">@Model.Evento.Data.ToShortDateString()</p>
        <p class="local fui-location">@Model.Evento.Local</p>
        <p class="quant-fotos-autor fui-camera">@Model.Evento.Arquivos.Count fotos por @Model.Evento.Creditos</p>
        <p class="visualizado fui-eye">@Model.Evento.Hits visualizações</p>
    </div>
    <h1 class="titulo-32px">@Model.Evento.Titulo</h1>
    @foreach (var arquivo in Model.Arquivos)
    {
        <div class="barra-compartilhar">
            <p class="left">Compartilhe a foto abaixo:</p>
            <ul class="compartilhar">
                <li><a class="face rpl" href="#" title="Compartilhar no Facebook">Facebook</a></li>
                <li><a class="gplus rpl" href="#" title="Compartilhar no Google Plus">Google Plus</a></li>
                <li><a class="twitter rpl" href="#" title="Compartilhar no Twitter">Twitter</a></li>
            </ul>
            <figure>
                <img src="@Foto.Placehold(arquivo.Nome, "940x529", "Evento")" width="940" />
            </figure>
        </div>
    }
</section>
<div class="bloco-largura-223px right">
    <div class="banner-223px right mgn-top-20px mgn-right-10px">
        <div class="texto-vertical left"></div>
        <div class="banner right">
            <figure>
                <a href="#" title="Título do banner">
                    <img src="img/banners/200x375px/img1.jpg" alt="">
                </a>
            </figure>
        </div>
    </div>
    <div class="banner-223px right mgn-top-20px mgn-right-10px">
        <div class="texto-vertical left"></div>
        <div class="banner right">
            <figure>
                <a href="#" title="Título do banner">
                    <img src="img/banners/200x375px/img2.jpg" alt="">
                </a>
            </figure>
        </div>
    </div>
    <div class="banner-223px right mgn-top-20px mgn-right-10px">
        <div class="texto-vertical left"></div>
        <div class="banner right">
            <figure>
                <a href="#" title="Título do banner">
                    <img src="img/banners/200x375px/img3.jpg" alt="">
                </a>
            </figure>
        </div>
    </div>
</div><!--fim bloco largura-->
<div class="paginacao left mgn-left-10px mgn-top-20px">
    <ul>
        @Html.PagedListPager(Model.Arquivos, page => Url.Action("Ler", new { page = page }))
    </ul>
</div>
<div class="banner-1184px right mgn-right-10px mgn-top-20px">
    <div class="banner-728px left">
        <div class="texto-vertical left"></div>
        <div class="banner right">
            <figure>
                <a href="#" title="Título do banner">
                    <img src="img/banners/728x90px/img4.png" alt="">
                </a>
            </figure>
        </div>
    </div>
    <div class="banner-417px right">
        <div class="texto-vertical left"></div>
        <div class="banner right">
            <figure>
                <a href="#" title="Título do banner">
                    <img src="img/banners/394x90px/img3.png" alt="">
                </a>
            </figure>
        </div>
    </div>
</div>