Eva.UI.Web/Areas/Painel/Controllers/ExtratorNewsController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CsQuery;
using Eva.Aplicacao;
using Eva.Dominio;
using PagedList;
using Eva.UI.Web.Helpers;

namespace Eva.UI.Web.Areas.Painel.Controllers
{
    public class ExtratorNewsController : Controller
    {
        private readonly ExtratorNewsAplicacao extratorNewsApp;

        public ExtratorNewsController()
        {
            extratorNewsApp = Fabrica.ExtratorNewsAplicacaoMongo();
        }

        public ActionResult Index(int? page)
        {
            var numeroDaPagina = page ?? 1;
            var listaPaginada = extratorNewsApp.ListarTodos().ToPagedList(numeroDaPagina, 10);

            return View(listaPaginada);
        }

        public ActionResult Editar(string id)
        {
            if (string.IsNullOrEmpty(id))
                return View(new ExtratorNews());

            var extrator = extratorNewsApp.ListarPorId(id);
            if (extrator == null)
            {
                this.Flash("Extrator News não encontrado!", FlashEnum.Error);
                return View(new ExtratorNews());
            }

            return View(extrator);
        }

        [HttpPost]
        public ActionResult Editar(ExtratorNews extrator)
        {
            if (!ModelState.IsValid)
                return View(extrator);


            extratorNewsApp.Salvar(extrator);
            this.Flash("Extrator News Salvo com Sucesso!");
            return RedirectToAction("Index");
        }

        public JsonResult Excluir(string id)
        {
            extratorNewsApp.Excluir(id);
            return Json("", JsonRequestBehavior.AllowGet);
        }

        public ActionResult VerLista(string id)
        {
            var extrator = Fabrica.ExtratorNewsAplicacaoMongo().ListarPorId(id);
            if (extrator == null)
            {
                return RedirectToAction("Index");
            }

            var html = GetHtml(extrator.Url);
            var query = CQ.Create(html);

            var linhas = query.Select(extrator.SeletorLista);

            var listaNoticiaCrawler = new List<NoticiasCrawler>();

            foreach (var item in linhas)
            {
                var temp = new NoticiasCrawler();

                var elemento = CQ.Create(item.InnerHTML);

                temp.Titulo = elemento.Select(extrator.SeletorTitulo).Text();
                temp.Url = elemento.Select(extrator.SeletorLink).Attr("href");
                listaNoticiaCrawler.Add(temp);
            }

            ViewBag.ExtratorNews = extrator;

            return View(listaNoticiaCrawler);
        }

        public ActionResult VerNoticia(string url, string id)
        {
            ViewBag.Url = url;
            ViewBag.Id = id;

            var extrator = Fabrica.ExtratorNewsAplicacaoMongo().ListarPorId(id);
            var items = Fabrica.ExtratorNewsItemAplicacaoMongo().ListarTodosPorIdExtratorNews(extrator.Id);

            if (!items.Any())
            {
                return RedirectToAction("Index");
            }

            var dados = new ExtratorNewsItem();
            //items filtrar baseado no começo da url
            foreach (var item in items)
            {
                if (url.Contains(item.Url))
                {
                    dados = item;
                    break;
                }
            }

            //mostrar erro
            if (string.IsNullOrEmpty(dados.Url))
            {
                this.Flash("Não foi possivel achar o item extrator para esta URL!", FlashEnum.Error);
                return View(new NoticiasConteudoCrawler());
            }


            if (string.IsNullOrEmpty(url))
                return RedirectToAction("Index");

            var html = GetHtml(url);
            var query = CQ.Create(html);

            var noticia = new NoticiasConteudoCrawler();

            noticia.Autor = query.Select(dados.SeletorAutor).Text();
            noticia.Titulo = query.Select(dados.SeletorTitulo).Text();
            noticia.Conteudo = query.Select(dados.SeletorConteudo).Text();
            noticia.UrlFoto = query.Select(dados.SeletorFoto).Attr("src");



            return View(noticia);
        }

        public ActionResult SalvarNoticia(NoticiasConteudoCrawler item)
        {
            item.Conteudo = item.Conteudo.UnHtml();
            var noticia = new Noticia()
            {
                Titulo = item.Titulo.UnHtml(),
                Conteudo = item.Conteudo,
                Data = DateTime.UtcNow.ToLocalTime(),
                Fonte = new Fonte() { Nome = item.Autor.UnHtml() },
                Resumo = item.Conteudo.Limit(120, " ..."),
                Publicado = false,
                ExibirComentarios = false,
            };

            Fabrica.NoticiaAplicacaoMongo().Salvar(noticia);

            GetImage(item.UrlFoto, noticia.Id);

            return RedirectToAction("Editar", "Noticia", new { id = noticia.Id });
        }

        private void GetImage(string url, string id)
        {
            if (string.IsNullOrEmpty(url))
                return;

            var name = Guid.NewGuid().ToString("N") + ".jpg";

            var imageStream = new WebClient().OpenRead(url);
            var img = Image.FromStream(imageStream);

            img.Save(Imagem.MontaPath("noticia", name));

            var noticia = Fabrica.NoticiaAplicacaoMongo().ListarPorId(id);

            noticia.Arquivos.Add(new Arquivo() { Nome = name, Legenda = noticia.Titulo, Ordem = 1 });
            Fabrica.NoticiaAplicacaoMongo().Salvar(noticia);

            Imagem.GeraArquivosBaseadoEmListaDeTamanhos(name, "noticia", ImagensLayout.Noticias);

        }

        private static string GetHtml(string url)
        {
            string htmlStringSource = string.Empty;
            try
            {
                HttpWebRequest request = (HttpWebRequest)HttpWebRequest.Create(url);
                request.ContentType = "application/x-www-form-urlencoded";
                request.UserAgent = "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:19.0) Gecko/20100101 Firefox/19.0";
                request.Method = "GET";
                request.Timeout = 30000;
                request.ReadWriteTimeout = 30000;
                request.KeepAlive = false;
                // make request for web page
                HttpWebResponse response = (HttpWebResponse)request.GetResponse();
                StreamReader htmlSource = new StreamReader(response.GetResponseStream());

                
                htmlStringSource = htmlSource.ReadToEnd();
                response.Close();
            }
            catch (Exception)
            {
                //Todo: mostrar o erro
                htmlStringSource = string.Empty;
            }

            return htmlStringSource;
        }
    }



    public class NoticiasCrawler
    {
        public string Titulo { get; set; }
        public string Url { get; set; }
    }


    public class NoticiasConteudoCrawler
    {
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public string Conteudo { get; set; }
        public string UrlFoto { get; set; }
    }

}

Eva.UI.Web/Areas/Painel/Controllers/ExtratorNewsItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eva.Aplicacao;
using Eva.Dominio;
using PagedList;

namespace Eva.UI.Web.Areas.Painel.Controllers
{
    public class ExtratorNewsItemController : Controller
    {
        private readonly ExtratorNewsItemAplicacao extratorNewsItemApp;
        private readonly ExtratorNewsAplicacao extratorNewsApp;


        public ExtratorNewsItemController()
        {
            extratorNewsItemApp = Fabrica.ExtratorNewsItemAplicacaoMongo();
            extratorNewsApp = Fabrica.ExtratorNewsAplicacaoMongo();

        }
        public ActionResult Index(string id, int? page)
        {
            var numeroDaPagina = page ?? 1;
            var listaPaginada = extratorNewsItemApp.ListarTodosPorIdExtratorNews(id).ToPagedList(numeroDaPagina, 10);
            var extratorNews = extratorNewsApp.ListarPorId(id);
            if (extratorNews == null)
                return HttpNotFound();
            ViewBag.ExtratorNews = extratorNews;

            return View(listaPaginada);
        }

        public ActionResult Editar(string id, string idExtrator)
        {
            var extratorNews = extratorNewsApp.ListarPorId(idExtrator);
            if (extratorNews == null)
                return HttpNotFound();
            ViewBag.ExtratorNews = extratorNews;

            if (string.IsNullOrEmpty(id))
                return View(new ExtratorNewsItem());

            var extratorNewsItem = extratorNewsItemApp.ListarPorId(id);
            if (extratorNewsItem == null)
            {
                this.Flash("Item não encontrado!", FlashEnum.Error);
                return View(new ExtratorNewsItem());
            }

            return View(extratorNewsItem);
        }

        [HttpPost]
        public ActionResult Editar(ExtratorNewsItem extratorNewsItem)
        {
            if (!ModelState.IsValid)
            {
                var extratorNews = extratorNewsApp.ListarPorId(extratorNewsItem.IdExtratorNews);
                ViewBag.ExtratorNews = extratorNews;
                return View(extratorNewsItem);
            }

            extratorNewsItemApp.Salvar(extratorNewsItem);
            this.Flash("Item Salvo com Sucesso!");
            return RedirectToAction("Index", new { Id = extratorNewsItem.IdExtratorNews });
        }

        public JsonResult Excluir(string id)
        {
            extratorNewsItemApp.Excluir(id);
            return Json("", JsonRequestBehavior.AllowGet);
        }
    }
}

Eva.UI.Web/Areas/Painel/Views/ExtratorNews/Editar.cshtml
@model Eva.Dominio.ExtratorNews

<div class="col-md-12">
    <!--breadcrumbs start -->
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home", new { Area = "Painel" })"><i class="fa fa-home"></i> Inicio</a></li>
        <li><a href="@Url.Action("Index", "ExtratorNews", new { Area = "Painel" })"><i class="fa fa-home"></i> Extrator News</a></li>
        <li class="active">Editar</li>
    </ul>
    <!--breadcrumbs end -->
</div>

<div class="col-lg-12">
    <section class="panel">
        <header class="panel-heading">
            @(string.IsNullOrEmpty(Model.Id) ? "Cadastrar novo extrator news" : "Editar extrator: " + Model.Nome)
        </header>
        <div class="panel-body">
            <div class="form">
                <form class="cmxform form-horizontal " id="grupoForm" method="POST" action="" novalidate="novalidate" enctype="multipart/form-data">

                    <div class="form-group ">
                        <label for="Nome" class="control-label col-lg-3">Nome:</label>
                        <div class="col-lg-6">
                            <input class=" form-control" id="Nome" name="Nome" type="text" value="@Model.Nome" required="" minlength="3">
                            <label for="Nome" class="error">@Html.ValidationMessageFor(x => x.Nome)</label>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="Url" class="control-label col-lg-3">Url:</label>
                        <div class="col-lg-6">
                            <input class=" form-control" id="Url" name="Url" type="text" value="@Model.Url" required="" minlength="5">
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="SeletorLista" class="control-label col-lg-3">Seletor Lista:</label>
                        <div class="col-lg-6">
                            <input class=" form-control" id="SeletorLista" name="SeletorLista" type="text" value="@Model.SeletorLista">
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="SeletorTitulo" class="control-label col-lg-3">Seletor Titulo:</label>
                        <div class="col-lg-6">
                            <input class=" form-control" id="SeletorTitulo" name="SeletorTitulo" type="text" value="@Model.SeletorTitulo">
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="SeletorLink" class="control-label col-lg-3">Seletor Link:</label>
                        <div class="col-lg-6">
                            <input class=" form-control" id="SeletorLink" name="SeletorLink" type="text" value="@Model.SeletorLink">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-offset-3 col-lg-6">
                            <button class="btn btn-primary" type="submit">Salvar</button>
                            <a href="@Url.Action("Index")" class="btn btn-default">Cancelar</a>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </section>
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script type="text/javascript" src="~/Scripts/bootstrap-fileupload.js"></script>

<script type="text/javascript">
    $("#grupoForm").validate({
        rules: {
            Nome: {
                required: true,
                minlength: 3
            },
            Url: {
                required: true,
                minlength: 5
            }
        },
        messages: {
            Nome: {
                required: "O campo nome é obrigatorio.",
                minlength: "O campo nome deve conter no mínimo 3 caracteres."
            },
            Url: {
                required: "O campo url é obrigatorio.",
                minlength: "O campo url deve conter no mínimo 3 caracteres."
            }
        }

    });
</script>

Eva.UI.Web/Areas/Painel/Views/ExtratorNews/Index.cshtml
@using Eva.Dominio
@using PagedList
@using PagedList.Mvc
@model IPagedList<Eva.Dominio.ExtratorNews>
<div class="col-md-12">
    <!--breadcrumbs start -->
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home", new { Area = "Painel" })"><i class="fa fa-home"></i> Inicio</a></li>
        <li class="active">Extrator News</li>
    </ul>
    <!--breadcrumbs end -->
</div>

<div class="col-md-12">
    @Flash.FlashMessage(TempData)
</div>

<div class="col-sm-12">
    <section class="panel">
        <header class="panel-heading">
            Extrator News
        </header>
        <div class="panel-body">
            <div class="adv-table editable-table ">
                <div class="clearfix" style="margin-bottom: 15px;">
                    <div class="btn-group">
                        <a href="@Url.Action("Editar")" class="btn btn-primary">
                            Novo Extrator <i class="fa fa-plus"></i>
                        </a>
                    </div>
                </div>

                <div id="editable-sample_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <table class="table table-hover general-table">
                        <thead>
                            <tr role="row">
                                <th>Nome</th>
                                <th style="width: 200px">Opções</th>
                            </tr>
                        </thead>

                        <tbody>
                            @if (Model.Any())
                            {
                                foreach (var extratorNews in Model)
                                {
                                    <tr id="@extratorNews.Id" data-nome="@extratorNews.Nome">

                                        <td>@extratorNews.Nome</td>
                                        <td>
                                            <a href="@Url.Action("VerLista", "ExtratorNews", new { Id = extratorNews.Id })" class="btn btn-white active tooltips" data-original-title="Ver" data-toggle="tooltip" title="Ver">
                                                <i class="fa fa-eye"></i>
                                            </a>
                                            <a href="@Url.Action("Index", "ExtratorNewsItem", new {Id = extratorNews.Id})" class="btn btn-white active tooltips" data-original-title="Items" data-toggle="tooltip" title="Adicionar Items">
                                                <i class="fa fa-tasks"></i>
                                            </a>
                                            <a href="@Url.Action("Editar", new {Id = extratorNews.Id})" class="btn btn-white active tooltips" data-original-title="Editar" data-toggle="tooltip">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            <a href="#" data-id="@extratorNews.Id" class="btn btn-white active" data-toggle="modal" data-target="#confimarExclusao">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="3">Não foi encontrado dados para a exibição</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="dataTables_paginate paging_bootstrap pagination pull-left">
                                @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }),
                                    new PagedListRenderOptions
                                    {
                                        UlElementClasses = Enumerable.Empty<string>(),
                                        DisplayPageCountAndCurrentLocation = true,
                                        PageCountAndCurrentLocationFormat = "Página {0} de {1}"

                                    })
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Modal Excluir Arquivos -->
            <div class="modal fade" id="confimarExclusao" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Confirmar exclusão</h4>
                        </div>

                        <div class="modal-body row">
                            <div class="col-md-12">
                                <h4 class="modal-title" id="myModalLabel">Deseja realmente excluir este item?</h4>
                                <br />
                                <h5 class="editNome"></h5>
                            </div>
                        </div>
                        <div class="modal-footer">

                            <button class="btn btn-danger" type="button" id="btnExcluirModal">Excluir</button>
                            <button data-dismiss="modal" aria-hidden="true" class="btn" type="button">Cancelar</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal-->

        </div>
    </section>
</div>
<script type="text/javascript">
    $(document).ready(function () {

        var itemAtual = {};
        $('#confimarExclusao').on('show.bs.modal', function (e) {
            carregaItemAtual(e.relatedTarget);

            $('.editNome').text(itemAtual.nome);

        });

        $('#btnExcluirModal').click(function () {
            $('#' + itemAtual.id).remove();

            $.ajax({
                url: "@Url.Action("Excluir")",
                type: "POST",
                data: JSON.stringify({ id: itemAtual.id }),
                contentType: 'application/json'
            });

            $('#confimarExclusao').modal('hide');
        });

        function carregaItemAtual(target) {
            itemAtual.id = $(target).data('id');
            itemAtual.nome = $('#' + itemAtual.id).data('nome');
        }
    });

</script>

Eva.UI.Web/Areas/Painel/Views/ExtratorNews/VerLista.cshtml
@model IEnumerable<Eva.UI.Web.Areas.Painel.Controllers.NoticiasCrawler>
<div class="col-md-12">
    <!--breadcrumbs start -->
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home", new {Area = "Painel"})"><i class="fa fa-home"></i> Inicio</a></li>
        <li><a href="@Url.Action("Index", "ExtratorNews", new { Area = "Painel" })"> Extrator News</a></li>
        <li class="active">Ver</li>
    </ul>
    <!--breadcrumbs end -->
</div>

<div class="col-md-12">
    @Flash.FlashMessage(TempData)
</div>

<div class="col-sm-12">
    <section class="panel">
        <header class="panel-heading">
            Extrator: <b>@ViewBag.ExtratorNews.Nome</b>
        </header>
        <div class="panel-body">
            <div class="adv-table editable-table ">
                
                <div id="editable-sample_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <table class="table table-hover general-table">
                        <thead>
                            <tr role="row">
                                <th>Titulo</th>
                                <th style="width: 105px">Opções</th>
                            </tr>
                        </thead>

                        <tbody>

                        @if (Model.Any())
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td><a href="@Url.Action("VerNoticia", "ExtratorNews", new { url = item.Url, id = ViewBag.ExtratorNews.Id })">@item.Titulo</a> </td>
                                        <td>
                                            <a href="" class="btn btn-white active tooltips" data-original-title="Editar" data-toggle="tooltip">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            <a href="#" data-id="" class="btn btn-white active" data-toggle="modal" data-target="#confimarExclusao">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="5">Não foi encontrado dados para a exibição</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                   
                </div>
            </div>
            
        </div>
    </section>
</div>

Eva.UI.Web/Areas/Painel/Views/ExtratorNews/VerNoticia.cshtml
@using PagedList.Mvc
@model Eva.UI.Web.Areas.Painel.Controllers.NoticiasConteudoCrawler
<div class="col-md-12">
    <!--breadcrumbs start -->
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home", new { Area = "Painel" })"><i class="fa fa-home"></i> Inicio</a></li>
        <li><a href="@Url.Action("Index", "ExtratorNews", new {Area = "Painel"})"> Extrator News</a></li>
        <li><a href="@Url.Action("VerLista", "ExtratorNews", new { Area = "Painel", id=ViewBag.Id })"> Ver Lista</a></li>
        <li class="active">Ver Noticia</li>
    </ul>
    <!--breadcrumbs end -->
</div>

<div class="col-md-12">
    @Flash.FlashMessage(TempData)
</div>

<div class="col-sm-12">
    <section class="panel">
        <header class="panel-heading">
            Extrator News:
        </header>
        <div class="panel-body">
            <div class="adv-table editable-table ">
                <a href="@ViewBag.Url" target="_blank">@ViewBag.Url</a>
                <div class="clearfix" style="margin-bottom: 15px;">
                    <div class="btn-group">
                        <form class="cmxform form-horizontal " id="grupoForm" method="POST" action="@Url.Action("SalvarNoticia")" novalidate="novalidate" enctype="multipart/form-data">

                            <input type="hidden" name="Titulo" id="Titulo" value="@Model.Titulo"/>
                            <input type="hidden" name="Autor" id="Autor" value="@Model.Autor"/>
                            <input type="hidden" name="UrlFoto" id="UrlFoto" value="@Model.UrlFoto"/>
                            <input type="hidden" name="Conteudo" id="Conteudo" value="@Model.Conteudo" />

                            <button class="btn btn-primary" type="submit">Publicar Noticia <i class="fa fa-plus"></i></button>
                        </form>
                    </div>
                </div>

                <div id="editable-sample_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1>@Model.Titulo</h1>
                            <em>@Model.Autor</em>
                            <div class="col-lg-12">
                                <img src="@Model.UrlFoto" alt="" />
                            </div>
                            <p>@Model.Conteudo</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
</div>