Eva.UI.Web/Areas/Painel/Controllers/FonteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eva.Aplicacao;
using Eva.Dominio;
using System.ComponentModel.DataAnnotations;
using Eva.UI.Web.Helpers;
using PagedList;

namespace Eva.UI.Web.Areas.Painel.Controllers
{
    public class FonteController : Controller
    {
       private readonly FonteAplicacao fonteApp;

        public FonteController()
        {
            fonteApp = Fabrica.FonteAplicacaoMongo();
        }
        public ActionResult Index(int? page)
        {

            var numeroDaPagina = page ?? 1;
            var listaPaginada = fonteApp.ListarTodos().ToPagedList(numeroDaPagina, 10);

            return View(listaPaginada);
        }

        public ActionResult Editar(string id)
        {
            if (string.IsNullOrEmpty(id))
                return View(new FonteViewModel());

            var fonte = fonteApp.ListarPorId(id);
            if (fonte == null)
            {
                this.Flash("Fonte não encontrada!", FlashEnum.Error);
                return View(new FonteViewModel());
            }

            var fonteViewModel = new FonteViewModel()
            {
                Id = fonte.Id,
                Nome = fonte.Nome
            };

            return View(fonteViewModel);
        }

        [HttpPost]
        public ActionResult Editar(FonteViewModel fonte)
        {
            if (!ModelState.IsValid) 
                return View(fonte);

            var fonteSalvar = new Fonte
            {
                Id = fonte.Id,
                Nome = fonte.Nome
            };

            fonteApp.Salvar(fonteSalvar);
            this.Flash("Fonte Salva com Sucesso!");
            return RedirectToAction("Index");
        }

        public JsonResult Excluir(string id)
        {
            Fabrica.FonteAplicacaoMongo().Excluir(id);
            return Json("", JsonRequestBehavior.AllowGet);
        }
	}

    public class FonteViewModel
    {
        public string Id { get; set; }
        [Required]
        public string Nome { get; set; }

    }
}

Eva.UI.Web/Areas/Painel/Controllers/NoticiaZonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eva.Aplicacao;
using Eva.Dominio;
using System.ComponentModel.DataAnnotations;
using PagedList;

namespace Eva.UI.Web.Areas.Painel.Controllers
{
    public class NoticiaZonaController : Controller
    {
       private readonly NoticiaZonaAplicacao noticiaZonaApp;

        public NoticiaZonaController()
        {
            noticiaZonaApp = Fabrica.NoticiaZonaAplicacaoMongo();
        }
        public ActionResult Index(int? page)
        {

            var numeroDaPagina = page ?? 1;
            var listaPaginada = noticiaZonaApp.ListarTodos().ToPagedList(numeroDaPagina, 10);

            return View(listaPaginada);
        }

        public ActionResult Editar(string id)
        {
            if (string.IsNullOrEmpty(id))
                return View(new NoticiaZonaViewModel());

            var noticiaZona = noticiaZonaApp.ListarPorId(id);
            if (noticiaZona == null)
            {
                this.Flash("Zona da Notícia não encontrada!", FlashEnum.Error);
                return View(new NoticiaZonaViewModel());
            }

            var noticiaZonaViewModel = new NoticiaZonaViewModel()
            {
                Id = noticiaZona.Id,
                Nome = noticiaZona.Nome
            };

            return View(noticiaZonaViewModel);
        }

        [HttpPost]
        public ActionResult Editar(NoticiaZonaViewModel noticiaZona)
        {
            if (!ModelState.IsValid) 
                return View(noticiaZona);

            var noticiaZonaSalvar = new NoticiaZona
            {
                Id = noticiaZona.Id,
                Nome = noticiaZona.Nome
            };

            noticiaZonaApp.Salvar(noticiaZonaSalvar);
            this.Flash("Zona da Notícia Salva com Sucesso!");
            return RedirectToAction("Index");
        }

        public JsonResult Excluir(string id)
        {
            Fabrica.NoticiaZonaAplicacaoMongo().Excluir(id);
            return Json("", JsonRequestBehavior.AllowGet);
        }
	}

    public class NoticiaZonaViewModel
    {
        public string Id { get; set; }
        [Required]
        public string Nome { get; set; }

    }
}

Eva.UI.Web/Areas/Painel/Views/NoticiaZona/Editar.cshtml
@model Eva.UI.Web.Areas.Painel.Controllers.NoticiaZonaViewModel

<div class="col-md-12">
    <!--breadcrumbs start -->
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home", new { Area = "Painel" })"><i class="fa fa-home"></i> Inicio</a></li>
        <li><a href="@Url.Action("Index", "Fonte", new { Area = "Painel" })"><i class="fa fa-home"></i> Zona da Notícia</a></li>
        <li class="active">Editar</li>
    </ul>
    <!--breadcrumbs end -->
</div>

<div class="col-lg-12">
    <section class="panel">
        <header class="panel-heading">
            @(string.IsNullOrEmpty(Model.Id) ? "Cadastrar nova zona da notícia" : "Editar zona da notícia: " + Model.Nome)
        </header>
        <div class="panel-body">
            <div class="form">
                <form class="cmxform form-horizontal " id="grupoForm" method="POST" action="" novalidate="novalidate" enctype="multipart/form-data">

                    <div class="form-group ">
                        <label for="Nome" class="control-label col-lg-3">Nome:</label>
                        <div class="col-lg-6">
                            <input class=" form-control" id="Nome" name="Nome" type="text" value="@Model.Nome" required="" minlength="3">
                            <label for="Nome" class="error">@Html.ValidationMessageFor(x => x.Nome)</label>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-offset-3 col-lg-6">
                            <button class="btn btn-primary" type="submit">Salvar</button>
                            <a href="@Url.Action("Index")" class="btn btn-default">Cancelar</a>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </section>
</div>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script type="text/javascript" src="~/Scripts/bootstrap-fileupload.js"></script>

<script type="text/javascript">
    $("#grupoForm").validate({
        rules: {
            Nome: {
                required: true,
                minlength: 3
            }
        },
        messages: {
            Nome: {
                required: "O campo nome é obrigatorio.",
                minlength: "O campo nome deve conter no mínimo 3 caracteres."
            }
        }

    });
</script>

Eva.UI.Web/Areas/Painel/Views/NoticiaZona/Index.cshtml
@using Eva.Dominio
@using PagedList
@using PagedList.Mvc
@model IPagedList<Eva.Dominio.NoticiaZona>
<div class="col-md-12">
    <!--breadcrumbs start -->
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home", new { Area = "Painel" })"><i class="fa fa-home"></i> Inicio</a></li>
        <li class="active">Zona da Notícia</li>
    </ul>
    <!--breadcrumbs end -->
</div>

<div class="col-md-12">
    @Flash.FlashMessage(TempData)
</div>

<div class="col-sm-12">
    <section class="panel">
        <header class="panel-heading">
            Grupos
        </header>
        <div class="panel-body">
            <div class="adv-table editable-table ">
                <div class="clearfix" style="margin-bottom: 15px;">
                    <div class="btn-group">
                        <a href="@Url.Action("Editar")" class="btn btn-primary">
                            Nova Zona de Notícia <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    <div class="btn-group pull-right">
                        <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            Tools <i class="fa fa-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="#">Print</a></li>
                            <li><a href="#">Save as PDF</a></li>
                            <li><a href="#">Export to Excel</a></li>
                        </ul>
                    </div>
                </div>

                <div id="editable-sample_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <table class="table table-hover general-table">
                        <thead>
                            <tr role="row">
                                <th>Nome</th>
                                <th style="width: 105px">Opções</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <form method="GET" action="" novalidate="novalidate">
                                    <td class=" "><input type="text" class="form-control small" id="nome" name="nome" type="text" value=""></td>
                                    <td class=" ">
                                        <button class="btn btn-primary" type="submit" class="btn btn-white active tooltips" data-original-title="Filtrar" data-toggle="tooltip">
                                            <i class="fa fa-search"></i>
                                        </button>
                                        <a href="#" class="btn btn-white active tooltips" data-original-title="Limpar" data-toggle="tooltip">
                                            <i class="fa fa-refresh"></i>
                                        </a>
                                    </td>
                                </form>
                            </tr>
                            @if (Model.Any())
                            {
                                foreach (var noticiaZona in Model)
                                {
                                    <tr id="@noticiaZona.Id" data-nome="@noticiaZona.Nome">

                                        <td>@noticiaZona.Nome</td>
                                        <td>
                                            <a href="@Url.Action("Editar", new { Id = noticiaZona.Id })" class="btn btn-white active tooltips" data-original-title="Editar" data-toggle="tooltip">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            <a href="#" data-id="@noticiaZona.Id" class="btn btn-white active" data-toggle="modal" data-target="#confimarExclusao">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="2">Não foi encontrado dados para a exibição</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="dataTables_paginate paging_bootstrap pagination pull-left">
                                @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }),
                                    new PagedListRenderOptions
                                    {
                                        UlElementClasses = Enumerable.Empty<string>(),
                                        DisplayPageCountAndCurrentLocation = true,
                                        PageCountAndCurrentLocationFormat = "Página {0} de {1}"

                                    })
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <!-- Modal Excluir Arquivos -->
            <div class="modal fade" id="confimarExclusao" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Confirmar exclusão</h4>
                        </div>

                        <div class="modal-body row">
                            <div class="col-md-12">
                                <h4 class="modal-title" id="myModalLabel">Deseja realmente excluir este item?</h4>
                                <br />
                                <h5 class="editNome"></h5>
                            </div>
                        </div>
                        <div class="modal-footer">

                            <button class="btn btn-danger" type="button" id="btnExcluirModal">Excluir</button>
                            <button data-dismiss="modal" aria-hidden="true" class="btn" type="button">Cancelar</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal-->

        </div>
    </section>
</div>
<script type="text/javascript">
    $(document).ready(function () {

        var itemAtual = {};
        $('#confimarExclusao').on('show.bs.modal', function (e) {
            carregaItemAtual(e.relatedTarget);

            $('.editNome').text(itemAtual.nome);

        });

        $('#btnExcluirModal').click(function () {
            $('#' + itemAtual.id).remove();

            $.ajax({
                url: "@Url.Action("Excluir")",
                type: "POST",
                data: JSON.stringify({ id: itemAtual.id }),
                contentType: 'application/json'
            });

            $('#confimarExclusao').modal('hide');
        });

        function carregaItemAtual(target) {
            itemAtual.id = $(target).data('id');
            itemAtual.nome = $('#' + itemAtual.id).data('nome');
        }
    });

</script>